[build]
publish = "dist"
command = "npm run build"

[functions]
  # Make environment variables available to edge functions
  included_files = ["**/*.json"]
  
[[edge_functions]]
  path = "/*"
  function = "entry.netlify-edge"
  [edge_functions.environment]
    QUIZ_URL = "${QUIZ_URL}"